### ISSUE TITLE
Rhythmbox 3.3 crashes on login

### ISSUE THREAD

**Issue by zhukovra** [radistmorse/rhythmbox-vk#6]
Hi! I'm using Rhythmbox 3.3 on Ubuntu 14.04 x64 (3.13.0-76-generic). When I try login to VK from Preferences window Rhythmbox crashes. `rhythmbox -d` output:

```
** Message: console message: https://oauth.vk.com/oauth/authorize?client_id=1922565&scope=audio,offline&redirect_uri=http://oauth.vk.com/blank.html&display=popup&response_type=token @31: TypeError: HTMLInputElement is not a function (evaluating 'ge('login_submit').submit()')

(rhythmbox:12802): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GObject'

(rhythmbox:12802): GLib-GObject-CRITICAL **: g_object_notify: assertion 'G_IS_OBJECT (object)' failed

(rhythmbox:12802): GLib-GObject-WARNING **: instance with invalid (NULL) class pointer

(rhythmbox:12802): GLib-GObject-CRITICAL **: g_signal_emit_by_name: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
fish: “rhythmbox -d” terminated by signal SIGSEGV (Address boundary error)
```

**Comment by radistmorse** [comment]
Wow, ubuntu is fast! I can't reproduce it in RB 3.2, and I don't see any clues as to what might be the case. We'll have to wait until RB 3.3 hits fedora.

**Comment by fossfreedom** [comment]
@radistmorse - at a guess its probably that webkit call in vk.py line 349.

give the console message in the trace - probably the uri property on wv is not being set/created correctly when wv.load_uri fails.  I suggest you need to trap a load_uri failure before trying to connect to the wv.uri property.

WebKit is deprecated and I know various fedora maintainers have been asking the rhythmbox maintainer to remove webkit from rhythmbox.  So you'll need to think about using webkit2 sooner rather than later because fedora will be pulling webkit from their repo's soon (at least for the next version of fedora).

**Comment by radistmorse** [comment]
Ok I'll see into it. But actually, this whole plugin may become deprecated quite soon. I'm pushing the patches that provide VK music for GNOME out of the box through GOA and grilo. Hopefully it'll make it in time for 3.20

**Comment by seriyps** [comment]
Sorry if it's unrelevant...
I use Ubuntu 15.10 with rhythmbox 3.2.1.

Initialy I was not able to activate plugin with following stacktrace:

```
Traceback (most recent call last):
  File "/home/seriy/.local/share/rhythmbox/plugins/vk/vk.py", line 17, in <module>
    from gi.repository import RB, Gio, Gtk, GdkPixbuf, GObject, Peas, PeasGtk, WebKit2
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 144, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name WebKit2, introspection typelib not found
```

So, I installed `gir1.2-webkit2-4.0`. Plugin was activated successfully, but when I tried to login Rhythmbox crashed with following output:

```
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
1   0xb3bf74c0 /usr/lib/i386-linux-gnu/libjavascriptcoregtk-3.0.so.0(WTFCrash+0x20) [0xb3bf74c0]
2   0xb3c30401 /usr/lib/i386-linux-gnu/libjavascriptcoregtk-3.0.so.0(_ZN3WTF10StringImplD1Ev+0x201) [0xb3c30401]
3   0xb3c304ba /usr/lib/i386-linux-gnu/libjavascriptcoregtk-3.0.so.0(_ZN3WTF10StringImpl7destroyEPS0_+0x1a) [0xb3c304ba]
4   0xa55318e9 /usr/lib/i386-linux-gnu/libwebkit2gtk-4.0.so.37(+0x2e28e9) [0xa55318e9]
5   0xa55335a7 /usr/lib/i386-linux-gnu/libwebkit2gtk-4.0.so.37(+0x2e45a7) [0xa55335a7]
6   0xa55338dc /usr/lib/i386-linux-gnu/libwebkit2gtk-4.0.so.37(+0x2e48dc) [0xa55338dc]
7   0xa505b748 /usr/lib/i386-linux-gnu/libjavascriptcoregtk-4.0.so.18(_ZN3WTF15GMainLoopSource12voidCallbackEv+0x88) [0xa505b748]
8   0xa5057ced /usr/lib/i386-linux-gnu/libjavascriptcoregtk-4.0.so.18(_ZN3WTF15GMainLoopSource18voidSourceCallbackEPS0_+0xd) [0xa5057ced]
9   0xb6b7b410 /lib/i386-linux-gnu/libglib-2.0.so.0(+0x43410) [0xb6b7b410]
10  0xb6b7eb9b /lib/i386-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x14b) [0xb6b7eb9b]
11  0xb6b7ef89 /lib/i386-linux-gnu/libglib-2.0.so.0(+0x46f89) [0xb6b7ef89]
12  0xb6b7f339 /lib/i386-linux-gnu/libglib-2.0.so.0(g_main_loop_run+0xf9) [0xb6b7f339]
13  0xa55e778d /usr/lib/i386-linux-gnu/libwebkit2gtk-4.0.so.37(+0x39878d) [0xa55e778d]
14  0xa5034f9f /usr/lib/i386-linux-gnu/libjavascriptcoregtk-4.0.so.18(+0x639f9f) [0xa5034f9f]
15  0xa5054399 /usr/lib/i386-linux-gnu/libjavascriptcoregtk-4.0.so.18(+0x659399) [0xa5054399]
16  0xb6b211aa /lib/i386-linux-gnu/libpthread.so.0(+0x61aa) [0xb6b211aa]
17  0xb6a4a4de /lib/i386-linux-gnu/libc.so.6(clone+0x5e) [0xb6a4a4de]
[1]    8494 segmentation fault (core dumped)  rhythmbox
```

I then removed previously installed package and installed another version of webkit-gtk `gir1.2-webkit2-3.0` and since then it works.
